### ISSUE TITLE
Why is the author's best run not good?

### ISSUE THREAD

**Issue by Yegiri** [kingyiusuen/image-to-latex#7]
I downloaded the author’s best run from wandb, and after experimentation, the results are as follows:
![image](https://user-images.githubusercontent.com/51883273/131104466-dcd2a098-a80b-46ef-b9bc-c9029094d9a6.png)
![image](https://user-images.githubusercontent.com/51883273/131104595-6af8a6be-c0f1-4a96-96c2-737f549cc630.png)

Did I download the wrong model?

**Comment by kingyiusuen** [comment]
Sorry to disappoint you, but even the best run has 17% character error rate :(

But it seems like the model works better if you resize the image to something closer to those in the training dataset.
<img width="743" alt="Screen Shot 2021-08-27 at 6 45 24 AM" src="https://user-images.githubusercontent.com/14181114/131122506-4291aeb8-ee73-43ba-b6e3-d1f432b3779c.png">

Also, this was meant to be a student project, so I stopped working on it after a month. I hope you can find a way to improve it.

**Comment by Yegiri** [comment]
Thank you for your reply!

**Comment by LMC63** [comment]
> Sorry to disappoint you, but even the best run has 17% character error rate :(
> 
> But it seems like the model works better if you resize the image to something closer to those in the training dataset.
> <img alt="Screen Shot 2021-08-27 at 6 45 24 AM" width="743" src="https://user-images.githubusercontent.com/14181114/131122506-4291aeb8-ee73-43ba-b6e3-d1f432b3779c.png">
> 
> Also, this was meant to be a student project, so I stopped working on it after a month. I hope you can find a way to improve it.

Dear sir, I met the same problem when converting polynomials, so what size should we convert the input to when using your best run model? @kingyiusuen 
![1](https://user-images.githubusercontent.com/48325810/133896677-8e2f4071-1508-49d2-b618-3573a0146c11.jpg)

![2](https://user-images.githubusercontent.com/48325810/133896672-d7fe8834-c53c-4e2a-83e1-f8a1260e2a6d.jpg)
